
//#include "api.h"

const char* str = "####################################################################################################################################################################################################################################";

typedef struct
{
	int x;
} XXXXXXXX;


typedef void (*F)(int x, int y, int (*a)());

struct test1 {
	int x;
	int y;
};

F f(int x);


struct test2;

typedef struct test3 {
	int x;
} test3_t;

#if 0

#include "api.h"

#ifndef SERIALIZE
#define SERIALIZE(...)
#endif

int func(int x)
{
	XSERIALIZE();

	/* Autogenerated: locals    /02-*/
	struct nrf_rpc_cbor_ctx ctx;
	size_t cbor_buffer_size_max = 5;
	int result;
	/* Autogenerated: end       //Re*/

	/* Autogenerated: allocate  /4Rw*/
	NRF_RPC_CBOR_ALLOC(ctx, cbor_buffer_size_max);
	/* Autogenerated: end       /38r*/

	/* Autogenerated: encode    /4Rw*/
	cbor_encode_int(&ctx.encoder, x);
	/* Autogenerated: end       /38r*/

	/* Autogenerated: send      /4Rw*/
	nrf_rpc_cbor_cmd_no_err(&entropy_group, RPC_COMMAND_ENTROPY_GET, &ctx,
			        ser_simple_rsp_int, &result);
	/* Autogenerated: end       /38r*/

	/* Autogenerated: return */
	return result;
	/* Autogenerated: end       /38r*/
}

SERIALIZE(HOST_FILE("api_host.c"));
SERIALIZE(HOST_FILE("api_host.c"));

int func2(int x)
{
	SERIALIZE();

	size_t cbor_buffer_size = NRF_RPC_CBOR_PROBE;				 /*##AJ/Vys4*/

	do {									 /*##Afd07Dc*/
		
		struct nrf_rpc_cbor_ctx ctx;					 /*####%AuAE*/
		int result;							 /*#####@64E*/

		SER_CBOR_ALLOC_PROBE(ctx, cbor_buffer_size);                     /*##A0Qai0Q*/

		x++;

		ser_cbor_encode_int(&ctx.encoder, x);				 /*##BBLyrGE*/

		if (cbor_buffer_size == NRF_RPC_CBOR_PROBE) {			 /*######%Bc*/
			cbor_buffer_size = nrf_rpc_cbor_needed(ctx);		 /*#######sb*/
			continue;						 /*#######bj*/
		}								 /*#######@8*/

		nrf_rpc_cbor_cmd_no_err(&entropy_group, RPC_COMMAND_ENTROPY_GET, &ctx, /*####%AOhn*/
				        ser_simple_rsp_int, &result);		       /*#####@ufc*/

		return result;							 /*##AoghAd0*/

	} while (1);								 /*##AiNLOg8*/
}

int func3(int x)
{
	SERIALIZE();
}

// // https://www.draw.io/#Hdoki-nordic%2Fdraw.io%2Fdrafts%2FUntitled%20Diagram.drawio

// /* COMMENT */

// #ifndef SERIALIZABLE
// #define SERIALIZABLE
// #endif

// /** @brief THE COMMENT
//  * 
//  * next line
//  *    indent
//  * 
//  * @noop SERIALIZABLE
//  * @SERIALIZABLE
//  * \noop SERIALIZABLE
//  * \SERIALIZABLE
//  */
// int func(int x, int *buf[])
// {
// 	SERIALIZABLE;
// 	printf("func: %d\n", x);
// }

// /* SERIALIZABLE */
// int func(int x, int *buf[]);

// #ifdef undefthink

// #include <stdio.h>

// typedef int (*callback_t)(int);
// typedef int (*callback_buf_t)(char* buf, int size);

// #ifndef SERIALIZE
// #define SERIALIZE(...)
// #endif

// #define _SERIALIZE(...)
// #define CALL_CALLBACK(type, callback, ...) (callback)(__VA_ARGS__)

// #define CALL_CALLBACK_NO_ARG(type, callback) type#_CALL(callback)
// #define CALL_CALLBACK(type, callback, ...) type#_CALL(__VA_ARGS__, callback)

// int func(int x)
// {
// 	SERIALIZE();
// 	printf("func: %d\n", x);
// }

// SERIALIZE(CALLBACK(callback_t));

// SERIALIZE(CALLBACK(callback_buf_t));
// SERIALIZE(ARRAY_SIZE(buf, size));
// SERIALIZE(OUT(buf));


// int callback_test(callback_t callback, int x)
// {
// 	return CALL_CALLBACK(callback_t, callback, x);
// }


// int buftest(int *arr, int size)
// {
// 	//SERIALIZE(ARRAY_SIZE(arr, size));
// 	//SERIALIZE(OUT(arr));
// 	//SERIALIZE(COPY);
// }

// #endif

// /* COMMENT2 */
#endif



#include "api.h"

#ifndef SERIALIZE
#define SERIALIZE(...)
#endif


static void func_rpc_handler(CborValue *packet, void *handler_data)
{
	/* Autogenerated: locals */
	bool decoding_ok;
	int x;
	int result;
	/* Autogenerated: end */

	/* Autogenerated: decoding */
	ser_cbor_decode_int(packet, &x);
	/* Autogenerated: end */

	/* Autogenerated: decoded */
	decoding_ok = ser_cbor_decoding_done(packet);
	/* Autogenerated: end */

	/* Autogenerated: execute */
	if (!decoding_ok) {
		ser_simple_response_void();
		return;
	}
	result = func(x);
	/* Autogenerated: end */

	/* Autogenerated: response */
	ser_simple_response_int(result);
	/* Autogenerated: end */
}

NRF_RPC_CBOR_CMD_DECODER(entropy_group, entropy_get,
			 RPC_COMMAND_ENTROPY_GET, entropy_get_handler,
			 (void *)CALL_TYPE_STANDARD);

// // https://www.draw.io/#Hdoki-nordic%2Fdraw.io%2Fdrafts%2FUntitled%20Diagram.drawio

// /* COMMENT */

// #ifndef SERIALIZABLE
// #define SERIALIZABLE
// #endif

// /** @brief THE COMMENT
//  * 
//  * next line
//  *    indent
//  * 
//  * @noop SERIALIZABLE
//  * @SERIALIZABLE
//  * \noop SERIALIZABLE
//  * \SERIALIZABLE
//  */
// int func(int x, int *buf[])
// {
// 	SERIALIZABLE;
// 	printf("func: %d\n", x);
// }

// /* SERIALIZABLE */
// int func(int x, int *buf[]);

// #ifdef undefthink

// #include <stdio.h>

// typedef int (*callback_t)(int);
// typedef int (*callback_buf_t)(char* buf, int size);

// #ifndef SERIALIZE
// #define SERIALIZE(...)
// #endif

// #define _SERIALIZE(...)
// #define CALL_CALLBACK(type, callback, ...) (callback)(__VA_ARGS__)

// #define CALL_CALLBACK_NO_ARG(type, callback) type#_CALL(callback)
// #define CALL_CALLBACK(type, callback, ...) type#_CALL(__VA_ARGS__, callback)

// int func(int x)
// {
// 	SERIALIZE();
// 	printf("func: %d\n", x);
// }

// SERIALIZE(CALLBACK(callback_t));

// SERIALIZE(CALLBACK(callback_buf_t));
// SERIALIZE(ARRAY_SIZE(buf, size));
// SERIALIZE(OUT(buf));


// int callback_test(callback_t callback, int x)
// {
// 	return CALL_CALLBACK(callback_t, callback, x);
// }


// int buftest(int *arr, int size)
// {
// 	//SERIALIZE(ARRAY_SIZE(arr, size));
// 	//SERIALIZE(OUT(arr));
// 	//SERIALIZE(COPY);
// }

// #endif

// /* COMMENT2 */



#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

int func(int x);

int (*send_something())(uint8_t *buffer, size_t size);


/*
//#include "nonex.h"

//#define SERIALIZABLE(...) __attribute__((deprecated("RP_SER_GEN_SERIALIZABLE" __VA_ARGS__)))
#define SERIALIZABLE(...) "RP_SER_GEN:" "SERIALIZABLE" __VA_ARGS__
#define SERIALIZE_PRE "RP_SER_GEN:" "PRE_SERIALIZE"


#define __SERIALIZATION_PRE "PREPRE"
#define __SERIALIZATION_POST "PSOT"
#define __SERIALIZATION_END "ENDNED"
#define __SERIALIZATION_ENCODER __attribute__((deprecated("RP_SER_GEN_SERIALIZABLE")))
#define __SERIALIZATION_DECODER __attribute__((deprecated("RP_SER_GEN_SERIALIZABLE")))

#define SERIALIZATION(arg) __SERIALIZATION_ ## arg

#ifndef SERIALIZATION
#define SERIALIZATION(...)
#endif


SERIALIZATION(ENCODER)
int funct(int x)
{
	int result;
	SERIALIZATION(PRE);
	SERIALIZATION(END);
	//...
	SERIALIZATION(POST);
	SERIALIZATION(END);
	return result;
}

#define AUTOGENERATED(...) "AUTOGENERATED:" __VA_ARGS__

#ifndef AUTOGENERATED
#define AUTOGENERATED(...)
#endif


SERIALIZATION(DECODER)
void funct_decoder(CborDecoder* in)
{
	/ * AUTOGENERATED: local variables * /
	int param_x;
	int result;
	/ * AUTOGENERATED: end * /

	AUTOGENERATED("decode input");
	param_x = cbor_decode_int(in);
	AUTOGENERATED("end");

	AUTOGENERATED("call target");
	result = funct(param_x);
	AUTOGENERATED("end");

	AUTOGENERATED("encode output");
	CREATE_CBOR_ENCODER(out, 5);
	cbor_encode(out, result);
	AUTOGENERATED("end");

	AUTOGENERATED("send response");
	send_response(out);
	AUTOGENERATED("end");
}

*/


#ifndef SERIALIZE
#define SERIALIZE(...)
#endif

#if !SERIALIZATION_DECODERS

struct Attr {
	char name[16];
	UUID id;
	int value;
	char* descr;
};

SERIALIZE(TYPE_CODERS(Attr, gatt_attr_encode, gatt_attr_decode));

/* Autogenerated: function      sjO */
int func(int x, int *buf[])
{
	#error This function was removed from the serialization interface, \
		but it contains a user code. Make sure that it is no longer \
		needed and delete it manually.
	SERIALIZE(OUT(buf));
	SERIALIZE(ARRAY_SIZE_CONST(buf, BUF_SIZE));
	SERIALIZE(ENC_BUF_SIZE(12))
	SERIALIZE(ENC_BUF_SIZE_ADJUST(-1))
	//SERIALIZE(ONE_PASS_ENCODING) - to force one pass: by default when buffer size is unpredictable two pass is generated
	/* Autogenerated: locals */
	int result;
	CborEncoder enc;
	CborParser dec;
	/* Autogenerated: end */

	/* Autogenerated: encode          utD */ // - 6-char hash of autogenerated block content (first 30-bits of e.g. MD5)
	cbor_encode_int(&enc, x);
	/* Autogenerated: end             -0/ */

	/* Autogenerated: send */
	rptrans_send(&enc, &dec);
	/* Autogenerated: end */

	/* Autogenerated: parse */
	result = cbor_get_int(&dec);
	/* Autogenerated: end */

	/* Autogenerated: return */
	return result;
	/* Autogenerated: end */
}
/* Autogenerated: end          /8L */

#else 

void func_decode(CborParser& in, CborEncoder& out)
{

}

#endif

static bool check_bt_addr_le_t(uint8_t size, uint8_t offset_type, uint8_t offset_a, uint8_t size_a, uint8_t* types)
{
	CHECK(sizeof(bt_addr_le_t) == size);
	CHECK(offsetof(bt_addr_le_t, type) == offset_type);
	CHECK(offsetof(bt_addr_le_t, a) == offset_a);
	CHECK(sizeof(((bt_addr_le_t*) NULL)->a) == size);
	CHECK(types[0] = BT_ADDR_LE_PUBLIC);
	CHECK(types[1] = BT_ADDR_LE_RANDOM);
	CHECK(types[2] = BT_ADDR_LE_PUBLIC_ID);
	CHECK(types[3] = BT_ADDR_LE_RANDOM_ID);
}

