

#include "api.h"

#ifndef SERIALIZE
#define SERIALIZE(...)
#endif

int func(int x)
{
	XSERIALIZE();

	/* Autogenerated: locals    /02-*/
	struct nrf_rpc_cbor_ctx ctx;
	size_t cbor_buffer_size_max = 5;
	int result;
	/* Autogenerated: end       //Re*/

	/* Autogenerated: allocate  /4Rw*/
	NRF_RPC_CBOR_ALLOC(ctx, cbor_buffer_size_max);
	/* Autogenerated: end       /38r*/

	/* Autogenerated: encode    /4Rw*/
	cbor_encode_int(&ctx.encoder, x);
	/* Autogenerated: end       /38r*/

	/* Autogenerated: send      /4Rw*/
	nrf_rpc_cbor_cmd_no_err(&entropy_group, RPC_COMMAND_ENTROPY_GET, &ctx,
			        ser_simple_rsp_int, &result);
	/* Autogenerated: end       /38r*/

	/* Autogenerated: return */
	return result;
	/* Autogenerated: end       /38r*/
}

SERIALIZE(HOST_FILE("api_host.c"));

int func2(int x)
{
	SERIALIZE();

	size_t cbor_buffer_size = NRF_RPC_CBOR_PROBE;				 /*##AJ/Vys4*/

	do {									 /*##Afd07Dc*/
		
		struct nrf_rpc_cbor_ctx ctx;					 /*####%AuAE*/
		int result;							 /*#####@64E*/

		SER_CBOR_ALLOC_PROBE(ctx, cbor_buffer_size);                     /*##A0Qai0Q*/

		x++;

		ser_cbor_encode_int(&ctx.encoder, x);				 /*##BBLyrGE*/

		if (cbor_buffer_size == NRF_RPC_CBOR_PROBE) {			 /*######%Bc*/
			cbor_buffer_size = nrf_rpc_cbor_needed(ctx);		 /*#######sb*/
			continue;						 /*#######bj*/
		}								 /*#######@8*/

		nrf_rpc_cbor_cmd_no_err(&entropy_group, RPC_COMMAND_ENTROPY_GET, &ctx, /*####%AOhn*/
				        ser_simple_rsp_int, &result);		       /*#####@ufc*/

		return result;							 /*##AoghAd0*/

	} while (1);								 /*##AiNLOg8*/
}

int func3(int x)
{
	SERIALIZE();
}

// // https://www.draw.io/#Hdoki-nordic%2Fdraw.io%2Fdrafts%2FUntitled%20Diagram.drawio

// /* COMMENT */

// #ifndef SERIALIZABLE
// #define SERIALIZABLE
// #endif

// /** @brief THE COMMENT
//  * 
//  * next line
//  *    indent
//  * 
//  * @noop SERIALIZABLE
//  * @SERIALIZABLE
//  * \noop SERIALIZABLE
//  * \SERIALIZABLE
//  */
// int func(int x, int *buf[])
// {
// 	SERIALIZABLE;
// 	printf("func: %d\n", x);
// }

// /* SERIALIZABLE */
// int func(int x, int *buf[]);

// #ifdef undefthink

// #include <stdio.h>

// typedef int (*callback_t)(int);
// typedef int (*callback_buf_t)(char* buf, int size);

// #ifndef SERIALIZE
// #define SERIALIZE(...)
// #endif

// #define _SERIALIZE(...)
// #define CALL_CALLBACK(type, callback, ...) (callback)(__VA_ARGS__)

// #define CALL_CALLBACK_NO_ARG(type, callback) type#_CALL(callback)
// #define CALL_CALLBACK(type, callback, ...) type#_CALL(__VA_ARGS__, callback)

// int func(int x)
// {
// 	SERIALIZE();
// 	printf("func: %d\n", x);
// }

// SERIALIZE(CALLBACK(callback_t));

// SERIALIZE(CALLBACK(callback_buf_t));
// SERIALIZE(ARRAY_SIZE(buf, size));
// SERIALIZE(OUT(buf));


// int callback_test(callback_t callback, int x)
// {
// 	return CALL_CALLBACK(callback_t, callback, x);
// }


// int buftest(int *arr, int size)
// {
// 	//SERIALIZE(ARRAY_SIZE(arr, size));
// 	//SERIALIZE(OUT(arr));
// 	//SERIALIZE(COPY);
// }

// #endif

// /* COMMENT2 */
