
#include <stdint.h>

#include "bluetooth/bluetooth.h"

/* WARNING!!! Partially autogenerated source file.
 *
 * Lines ending with special comment starting with ## are autogenerated and
 * should not be changed manually. Group of autogenerated lines should not be
 * splitted.
 */

SERIALIZE(HOST_FILE("bt_gap_host.c"));
SERIALIZE(CMD_ID(, _RPC_CMD));
SERIALIZE(EVT_ID(, _RPC_EVT));
SERIALIZE(GROUP(bt_rpc_grp));

SERIALIZE(RAW_STRUCT(bt_addr_le_t));
SERIALIZE(RAW_STRUCT(struct bt_bond_info));
SERIALIZE(RAW_STRUCT(struct bt_le_ext_adv_sent_info));
SERIALIZE(RAW_STRUCT(struct bt_le_ext_adv_scanned_info));
SERIALIZE(OPAQUE_STRUCT(void));
SERIALIZE(OPAQUE_STRUCT(struct bt_le_ext_adv));
SERIALIZE(OPAQUE_STRUCT(struct bt_conn));


#define MAX_BT_NAME_LENGTH 128


int bt_enable(bt_ready_cb_t cb)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%Aa*/
	int _result;                                                             /*######Qso*/
	size_t _buffer_size_max = 5;                                             /*######@uA*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_callback(&_ctx.encoder, cb);                                  /*##AxNS7A4*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_ENABLE_RPC_CMD,                  /*####%BKRK*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@M9g*/

	return _result;                                                          /*##BX7TDLc*/
}


int bt_set_name(const char *name)
{
	SERIALIZE(STR(name));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*#######%A*/
	size_t _name_strlen;                                                     /*#######bk*/
	int _result;                                                             /*#######HH*/
	size_t _scratchpad_size = 0;                                             /*#######eY*/
	size_t _buffer_size_max = 10;                                            /*########@*/

	_name_strlen = strlen(name);                                             /*####%CFOk*/
	_buffer_size_max += _name_strlen;                                        /*#####@f8c*/

	_scratchpad_size += SCRATCHPAD_ALIGN(_name_strlen + 1);                  /*##EObZcVc*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*####%AoDN*/
	ser_encode_uint(&_ctx.encoder, _scratchpad_size);                        /*#####@BNc*/

	ser_encode_str(&_ctx.encoder, name, _name_strlen);                       /*##A/RUZRo*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_SET_NAME_RPC_CMD,                /*####%BKgG*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@0j4*/

	return _result;                                                          /*##BX7TDLc*/
}


struct bt_get_name_out_rpc_res                                                   /*####%Bp8J*/
{                                                                                /*#####@zYc*/

	bool _result;                                                            /*######%CW*/
	size_t size;                                                             /*######pln*/
	char * name;                                                             /*######@DY*/

};                                                                               /*##B985gv0*/

static void bt_get_name_out_rpc_rsp(CborValue *_value, void *_handler_data)      /*####%BoL7*/
{                                                                                /*#####@fvE*/

	struct entropy_get_result *_res =                                        /*####%Afvn*/
		(struct bt_get_name_out_rpc_res *)_handler_data;                 /*#####@jyA*/

	_res->_result = ser_decode_bool(_value);                                 /*####%DYid*/
	ser_decode_str(_value, _res->name, (_res->size));                        /*#####@AWM*/

}                                                                                /*##B9ELNqo*/

static bool bt_get_name_out(char *name, size_t size)
{
	SERIALIZE(OUT(name));
	SERIALIZE(STR(name));
	SERIALIZE(SIZE_PARAM(name, size));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AY*/
	struct bt_get_name_out_rpc_res _result;                                  /*#######X2*/
	size_t _scratchpad_size = 0;                                             /*#######Jd*/
	size_t _buffer_size_max = 10;                                            /*#######@I*/

	_scratchpad_size += SCRATCHPAD_ALIGN(size);                              /*##EB+3ycA*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*####%AoDN*/
	ser_encode_uint(&_ctx.encoder, _scratchpad_size);                        /*#####@BNc*/

	ser_encode_uint(&_ctx.encoder, size);                                    /*##A2nPHkE*/

	_result.size = size;                                                     /*####%C5M6*/
	_result.name = name;                                                     /*#####@4K4*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_GET_NAME_OUT_RPC_CMD,            /*####%BG0o*/
		&_ctx, bt_get_name_out_rpc_rsp, &_result);                       /*#####@sSg*/

	return _result._result;                                                  /*##BW0ge3U*/
}


const char *bt_get_name(void)
{
	static char bt_name_cache[MAX_BT_NAME_LENGTH];
	bool not_null;

	not_null = bt_get_name_out(bt_name_cache, sizeof(bt_name_cache));
	return not_null ? bt_name_cache : NULL;
}


int bt_set_id_addr(const bt_addr_le_t *addr)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AR*/
	int _result;                                                             /*######RDP*/
	size_t _buffer_size_max = 3;                                             /*######@sI*/

	_buffer_size_max += addr ? sizeof(bt_addr_le_t) : 0;                     /*##CHCgvU0*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_buffer(&_ctx.encoder, addr, sizeof(bt_addr_le_t));            /*##A9rQrRg*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_SET_ID_ADDR_RPC_CMD,             /*####%BG6w*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@qi0*/

	return _result;                                                          /*##BX7TDLc*/
}


int bt_id_delete(uint8_t id)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AW*/
	int _result;                                                             /*######sOU*/
	size_t _buffer_size_max = 2;                                             /*######@TQ*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_uint(&_ctx.encoder, id);                                      /*##A9BnOB4*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_ID_DELETE_RPC_CMD,               /*####%BNTu*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@K8I*/

	return _result;                                                          /*##BX7TDLc*/
}


int bt_le_adv_stop(void)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AX*/
	int _result;                                                             /*######56+*/
	size_t _buffer_size_max = 0;                                             /*######@io*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_ADV_STOP_RPC_CMD,             /*####%BIpx*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@3mk*/

	return _result;                                                          /*##BX7TDLc*/
}


int bt_le_scan_stop(void)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AX*/
	int _result;                                                             /*######56+*/
	size_t _buffer_size_max = 0;                                             /*######@io*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_SCAN_STOP_RPC_CMD,            /*####%BG0S*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@eME*/

	return _result;                                                          /*##BX7TDLc*/
}


static void bt_le_scan_cb_reg_enable(void)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*####%ATMv*/
	size_t _buffer_size_max = 0;                                             /*#####@1d4*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_SCAN_CB_REG_ENABLE_RPC_CMD,   /*####%BHTs*/
		&_ctx, ser_rsp_simple_void, NULL);                               /*#####@6UQ*/
}


static node_t scan_cb_list;


void bt_le_scan_cb_register(struct bt_le_scan_cb *cb)
{
	bool wasEmpty = true; // TODO: check if list is empty
	// TODO: add to scan_cb_list
	if (wasEmpty) {
		bt_le_scan_cb_reg_enable();
	}
}


int bt_le_whitelist_clear(void)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AX*/
	int _result;                                                             /*######56+*/
	size_t _buffer_size_max = 0;                                             /*######@io*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_WHITELIST_CLEAR_RPC_CMD,      /*####%BBSY*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@ClQ*/

	return _result;                                                          /*##BX7TDLc*/
}


int bt_le_set_chan_map(uint8_t chan_map[5])
{
	SERIALIZE(SIZE(chan_map, 5));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*#######%A*/
	size_t _chan_map_size;                                                   /*#######Sz*/
	int _result;                                                             /*#######xQ*/
	size_t _scratchpad_size = 0;                                             /*#######pA*/
	size_t _buffer_size_max = 10;                                            /*########@*/

	_chan_map_size = sizeof(uint8_t) * 5;                                    /*####%CGlM*/
	_buffer_size_max += _chan_map_size;                                      /*#####@6lU*/

	_scratchpad_size += SCRATCHPAD_ALIGN(_chan_map_size);                    /*##EJHhpZ4*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*####%AoDN*/
	ser_encode_uint(&_ctx.encoder, _scratchpad_size);                        /*#####@BNc*/

	ser_encode_buffer(&_ctx.encoder, chan_map, _chan_map_size);              /*##A4qUuxk*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_SET_CHAN_MAP_RPC_CMD,         /*####%BCta*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@i9M*/

	return _result;                                                          /*##BX7TDLc*/
}


int bt_br_discovery_stop(void)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AX*/
	int _result;                                                             /*######56+*/
	size_t _buffer_size_max = 0;                                             /*######@io*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_BR_DISCOVERY_STOP_RPC_CMD,       /*####%BB+X*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@piE*/

	return _result;                                                          /*##BX7TDLc*/
}

int bt_br_set_discoverable(bool enable)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AU*/
	int _result;                                                             /*######ulr*/
	size_t _buffer_size_max = 1;                                             /*######@jw*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_bool(&_ctx.encoder, enable);                                  /*##AyLT/1M*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_BR_SET_DISCOVERABLE_RPC_CMD,     /*####%BLiS*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@PD8*/

	return _result;                                                          /*##BX7TDLc*/
}

int bt_br_set_connectable(bool enable)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AU*/
	int _result;                                                             /*######ulr*/
	size_t _buffer_size_max = 1;                                             /*######@jw*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_bool(&_ctx.encoder, enable);                                  /*##AyLT/1M*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_BR_SET_CONNECTABLE_RPC_CMD,      /*####%BIit*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@tFI*/

	return _result;                                                          /*##BX7TDLc*/
}

static void bt_le_scan_timeout_rpc_handler(CborValue *_value, void *_handler_data)/*####%BrQA*/
{                                                                                 /*#####@ZO0*/

	nrf_rpc_cbor_decoding_done(_value);                                       /*##AGkSPWY*/

	bt_le_scan_timeout();                                                     /*##DtLGskE*/

}                                                                                 /*##B9ELNqo*/


struct bt_id_get_rpc_res                                                         /*####%Bmxc*/
{                                                                                /*#####@ZAo*/

	size_t * count;                                                          /*####%CcVF*/
	bt_addr_le_t * addrs;                                                    /*#####@Nco*/

};                                                                               /*##B985gv0*/

static void bt_id_get_rpc_rsp(CborValue *_value, void *_handler_data)                 /*####%BluI*/
{                                                                                     /*#####@1Q4*/

	struct entropy_get_result *_res =                                             /*####%AdCx*/
		(struct bt_id_get_rpc_res *)_handler_data;                            /*#####@7T0*/

	*(_res->count) = ser_decode_uint(_value);                                     /*####%DZiC*/
	ser_decode_buffer(_value, _res->addrs, *(_res->count) * sizeof(bt_addr_le_t));/*#####@Ip8*/

}                                                                                     /*##B9ELNqo*/

void bt_id_get(bt_addr_le_t *addrs, size_t *count)
{
	SERIALIZE(OUT(addrs));
	SERIALIZE(SIZE_PARAM_EX(addrs, *$, count));
	SERIALIZE(INOUT(count));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AU*/
	struct bt_id_get_rpc_res _result;                                        /*#######FC*/
	size_t _scratchpad_size = 0;                                             /*#######Cq*/
	size_t _buffer_size_max = 10;                                            /*#######@o*/

	_scratchpad_size += SCRATCHPAD_ALIGN(*count * sizeof(bt_addr_le_t));     /*##EM0RMfw*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*####%AoDN*/
	ser_encode_uint(&_ctx.encoder, _scratchpad_size);                        /*#####@BNc*/

	ser_encode_uint(&_ctx.encoder, *count);                                  /*##A0IY0+8*/

	_result.count = count;                                                   /*####%C9M/*/
	_result.addrs = addrs;                                                   /*#####@zo8*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_ID_GET_RPC_CMD,                  /*####%BLnI*/
		&_ctx, bt_id_get_rpc_rsp, &_result);                             /*#####@SsE*/
}


uint8_t generate_addr_irk_flags(bt_addr_le_t *addr, uint8_t *irk)
{
	uint8_t flags = 0;

	if (irk) {
		for (int i = 0; i < 16; i++) {
			if (irk[i] != 0) {
				flags |= 1;
				break;
			}
		}
	}

	if (addr) {
		static const bt_addr_le_t any = BT_ADDR_LE_ANY;
		if (memcmp(&any, addr) != 0) {
			flags |= 2;
		}
	}

	return flags;
}

struct bt_id_create_rpc_res                                                      /*####%BoIG*/
{                                                                                /*#####@PlM*/

	int _result;                                                             /*######%CT*/
	bt_addr_le_t * addr;                                                     /*######Jyh*/
	uint8_t * irk;                                                           /*######@+s*/

};                                                                               /*##B985gv0*/

static void bt_id_create_rpc_rsp(CborValue *_value, void *_handler_data)         /*####%BqRo*/
{                                                                                /*#####@GSg*/

	struct entropy_get_result *_res =                                        /*####%AWX7*/
		(struct bt_id_create_rpc_res *)_handler_data;                    /*#####@L6A*/

	_res->_result = ser_decode_int(_value);                                  /*######%DQ*/
	ser_decode_buffer(_value, _res->addr, sizeof(bt_addr_le_t));             /*######lk5*/
	ser_decode_buffer(_value, _res->irk, sizeof(uint8_t) * 16);              /*######@5o*/

}                                                                                /*##B9ELNqo*/

int bt_id_create(bt_addr_le_t *addr, uint8_t *irk)
{
	SERIALIZE(NULLABLE(addr));
	SERIALIZE(INOUT(addr));
	SERIALIZE(NULLABLE(irk));
	SERIALIZE(INOUT(irk));
	SERIALIZE(SIZE(irk, 16));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*#######%A*/
	size_t _irk_size;                                                        /*#######Xr*/
	struct bt_id_create_rpc_res _result;                                     /*#######Lm*/
	size_t _scratchpad_size = 0;                                             /*#######Ak*/
	size_t _buffer_size_max = 13;                                            /*########@*/

	size_t i;

	_buffer_size_max += addr ? sizeof(bt_addr_le_t) : 0;                     /*######%CB*/
	_irk_size = !irk ? 0 : sizeof(uint8_t) * 16;                             /*######cKg*/
	_buffer_size_max += _irk_size;                                           /*######@u4*/

	_buffer_size_max += 1;

	_scratchpad_size += SCRATCHPAD_ALIGN(_irk_size);                         /*##ELqQtKI*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*####%AoDN*/
	ser_encode_uint(&_ctx.encoder, _scratchpad_size);                        /*#####@BNc*/

	ser_encode_buffer(&_ctx.encoder, addr, sizeof(bt_addr_le_t));            /*####%Ax4U*/
	ser_encode_buffer(&_ctx.encoder, irk, _irk_size);                        /*#####@/YU*/

	ser_encode_uint(generate_addr_irk_flags(addr, irk));

	_result.addr = addr;                                                     /*####%CxTc*/
	_result.irk = irk;                                                       /*#####@QsM*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_ID_CREATE_RPC_CMD,               /*####%BMH+*/
		&_ctx, bt_id_create_rpc_rsp, &_result);                          /*#####@log*/

	return _result._result;                                                  /*##BW0ge3U*/
}


struct bt_id_reset_rpc_res                                                       /*####%Bs1i*/
{                                                                                /*#####@i/M*/

	int _result;                                                             /*######%CT*/
	bt_addr_le_t * addr;                                                     /*######Jyh*/
	uint8_t * irk;                                                           /*######@+s*/

};                                                                               /*##B985gv0*/

static void bt_id_reset_rpc_rsp(CborValue *_value, void *_handler_data)          /*####%BoSY*/
{                                                                                /*#####@/xk*/

	struct entropy_get_result *_res =                                        /*####%AYXk*/
		(struct bt_id_reset_rpc_res *)_handler_data;                     /*#####@RoU*/

	_res->_result = ser_decode_int(_value);                                  /*######%DQ*/
	ser_decode_buffer(_value, _res->addr, sizeof(bt_addr_le_t));             /*######lk5*/
	ser_decode_buffer(_value, _res->irk, sizeof(uint8_t) * 16);              /*######@5o*/

}                                                                                /*##B9ELNqo*/

int bt_id_reset(u8_t id, bt_addr_le_t *addr, uint8_t *irk)
{
	SERIALIZE(INOUT(addr));
	SERIALIZE(NULLABLE(addr));
	SERIALIZE(INOUT(irk));
	SERIALIZE(NULLABLE(irk));
	SERIALIZE(SIZE(irk, 16));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*#######%A*/
	size_t _irk_size;                                                        /*#######VA*/
	struct bt_id_reset_rpc_res _result;                                      /*#######80*/
	size_t _scratchpad_size = 0;                                             /*#######ao*/
	size_t _buffer_size_max = 18;                                            /*########@*/

	_buffer_size_max += addr ? sizeof(bt_addr_le_t) : 0;                     /*######%CB*/
	_irk_size = !irk ? 0 : sizeof(uint8_t) * 16;                             /*######cKg*/
	_buffer_size_max += _irk_size;                                           /*######@u4*/

	_scratchpad_size += SCRATCHPAD_ALIGN(_irk_size);                         /*##ELqQtKI*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*####%AoDN*/
	ser_encode_uint(&_ctx.encoder, _scratchpad_size);                        /*#####@BNc*/

	ser_encode_int(&_ctx.encoder, id);                                       /*######%Aw*/
	ser_encode_buffer(&_ctx.encoder, addr, sizeof(bt_addr_le_t));            /*######bYz*/
	ser_encode_buffer(&_ctx.encoder, irk, _irk_size);                        /*######@+4*/

	ser_encode_uint(generate_addr_irk_flags(addr, irk));

	_result.addr = addr;                                                     /*####%CxTc*/
	_result.irk = irk;                                                       /*#####@QsM*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_ID_RESET_RPC_CMD,                /*####%BDbH*/
		&_ctx, bt_id_reset_rpc_rsp, &_result);                           /*#####@DeY*/

	return _result._result;                                                  /*##BW0ge3U*/
}


size_t bt_le_adv_param_sp_size(struct bt_le_adv_param *_data)                         /*####%Bhf3*/
{                                                                                     /*#####@LEI*/

	size_t _scratchpad_size = 0;                                                  /*##ATz5YrA*/

	_scratchpad_size += !_data->peer ? 0 : SCRATCHPAD_ALIGN(sizeof(bt_addr_le_t));/*##EL1Agek*/

	return _scratchpad_size;                                                      /*##BRWAmyU*/

}                                                                                     /*##B9ELNqo*/

size_t bt_le_adv_param_buf_size(struct bt_le_adv_param *_data)                   /*####%BvWP*/
{                                                                                /*#####@qjc*/

	size_t _buffer_size_max = 0;                                             /*##AW2oACE*/

	_buffer_size_max += !_data->peer ? 0 : 2 + sizeof(bt_addr_le_t);         /*##CASBfgs*/

	return _buffer_size_max;                                                 /*##BWmN6G8*/

}                                                                                /*##B9ELNqo*/

void bt_le_adv_param_enc(CborEncoder *_encoder, struct bt_le_adv_param *_data)   /*####%BmQP*/
{                                                                                /*#####@RZs*/

	SERIALIZE(STRUCT(struct bt_le_adv_param));
	SERIALIZE(NULLABLE(peer));

	ser_encode_uint(_encoder, _data->id);                                    /*#######%A*/
	ser_encode_uint(_encoder, _data->sid);                                   /*#######zA*/
	ser_encode_uint(_encoder, _data->secondary_max_skip);                    /*########f*/
	ser_encode_uint(_encoder, _data->options);                               /*########O*/
	ser_encode_uint(_encoder, _data->interval_min);                          /*########T*/
	ser_encode_uint(_encoder, _data->interval_max);                          /*########M*/
	ser_encode_buffer(_encoder, &_data->peer, sizeof(bt_addr_le_t));         /*########@*/

}                                                                                /*##B9ELNqo*/


size_t bt_data_buf_size(struct bt_data *_data)                                   /*####%Bh+W*/
{                                                                                /*#####@gQY*/

	size_t _buffer_size_max = 0;                                             /*##AW2oACE*/

	_buffer_size_max += sizeof(uint8_t) * _data->data_len;                   /*##CBQ2Maw*/

	return _buffer_size_max;                                                 /*##BWmN6G8*/

}                                                                                /*##B9ELNqo*/

size_t bt_data_sp_size(struct bt_data *_data)                                    /*####%Bpd6*/
{                                                                                /*#####@6Xk*/

	size_t _scratchpad_size = 0;                                             /*##ATz5YrA*/

	_scratchpad_size += SCRATCHPAD_ALIGN(sizeof(uint8_t) * _data->data_len); /*##EGeYfNs*/

	return _scratchpad_size;                                                 /*##BRWAmyU*/

}                                                                                /*##B9ELNqo*/

void bt_data_enc(CborEncoder *_encoder, struct bt_data *_data)                      /*####%Brep*/
{                                                                                   /*#####@Iq0*/

	SERIALIZE(STRUCT(struct bt_data));
	SERIALIZE(SIZE_PARAM(data, data_len));

	ser_encode_uint(_encoder, _data->type);                                     /*######%A8*/
	ser_encode_uint(_encoder, _data->data_len);                                 /*######fsW*/
	ser_encode_buffer(_encoder, _data->data, sizeof(uint8_t) * _data->data_len);/*######@EY*/

}                                                                                   /*##B9ELNqo*/


int bt_le_adv_start(const struct bt_le_adv_param *param,
		    const struct bt_data *ad, size_t ad_len,
		    const struct bt_data *sd, size_t sd_len)
{
	SERIALIZE(SIZE_PARAM(ad, ad_len));
	SERIALIZE(SIZE_PARAM(sd, sd_len));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*#######%A*/
	int _result;                                                             /*#######Vr*/
	size_t _scratchpad_size = 0;                                             /*#######45*/
	size_t _buffer_size_max = 37;                                            /*#######io*/
	size_t _i;                                                               /*########@*/

	_buffer_size_max += bt_le_adv_param_buf_size(param);                     /*########%*/
	for (_i = 0; _i < ad_len; _i++) {                                        /*########C*/
		_buffer_size_max += bt_data_buf_size(&ad[_i]);                   /*########N*/
		_scratchpad_size += SCRATCHPAD_ALIGN(sizeof(struct bt_data));    /*########1*/
		_scratchpad_size += bt_data_sp_size(&ad[_i]);                    /*########8*/
	}                                                                        /*########F*/
	for (_i = 0; _i < sd_len; _i++) {                                        /*########7*/
		_buffer_size_max += bt_data_buf_size(&sd[_i]);                   /*########o*/
		_scratchpad_size += SCRATCHPAD_ALIGN(sizeof(struct bt_data));    /*#########*/
		_scratchpad_size += bt_data_sp_size(&sd[_i]);                    /*#########*/
	}                                                                        /*########@*/

	_scratchpad_size += bt_le_adv_param_sp_size(param);                      /*##EEZ/Gv4*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*####%AoDN*/
	ser_encode_uint(&_ctx.encoder, _scratchpad_size);                        /*#####@BNc*/

	bt_le_adv_param_enc(&_ctx.encoder, param);                               /*########%*/
	ser_encode_uint(&_ctx.encoder, ad_len);                                  /*########A*/
	for (_i = 0; _i < ad_len; _i++) {                                        /*########+*/
		bt_data_enc(&_ctx.encoder, &ad[_i]);                             /*########o*/
	}                                                                        /*########a*/
	ser_encode_uint(&_ctx.encoder, sd_len);                                  /*########E*/
	for (_i = 0; _i < sd_len; _i++) {                                        /*########B*/
		bt_data_enc(&_ctx.encoder, &sd[_i]);                             /*########g*/
	}                                                                        /*########@*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_ADV_START_RPC_CMD,            /*####%BNew*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@Uc8*/

	return _result;                                                          /*##BX7TDLc*/
}


int bt_le_adv_update_data(const struct bt_data *ad, size_t ad_len,
			  const struct bt_data *sd, size_t sd_len)
{
	SERIALIZE(SIZE_PARAM(ad, ad_len));
	SERIALIZE(SIZE_PARAM(sd, sd_len));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*#######%A*/
	int _result;                                                             /*#######dr*/
	size_t _scratchpad_size = 0;                                             /*#######k2*/
	size_t _buffer_size_max = 15;                                            /*#######pA*/
	size_t _i;                                                               /*########@*/

	for (_i = 0; _i < ad_len; _i++) {                                        /*########%*/
		_buffer_size_max += bt_data_buf_size(&ad[_i]);                   /*########C*/
		_scratchpad_size += SCRATCHPAD_ALIGN(sizeof(struct bt_data));    /*########J*/
		_scratchpad_size += bt_data_sp_size(&ad[_i]);                    /*########/*/
	}                                                                        /*########m*/
	for (_i = 0; _i < sd_len; _i++) {                                        /*########7*/
		_buffer_size_max += bt_data_buf_size(&sd[_i]);                   /*########f*/
		_scratchpad_size += SCRATCHPAD_ALIGN(sizeof(struct bt_data));    /*########M*/
		_scratchpad_size += bt_data_sp_size(&sd[_i]);                    /*#########*/
	}                                                                        /*########@*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*####%AoDN*/
	ser_encode_uint(&_ctx.encoder, _scratchpad_size);                        /*#####@BNc*/

	ser_encode_uint(&_ctx.encoder, ad_len);                                  /*#######%A*/
	for (_i = 0; _i < ad_len; _i++) {                                        /*########/*/
		bt_data_enc(&_ctx.encoder, &ad[_i]);                             /*########P*/
	}                                                                        /*########G*/
	ser_encode_uint(&_ctx.encoder, sd_len);                                  /*########S*/
	for (_i = 0; _i < sd_len; _i++) {                                        /*########r*/
		bt_data_enc(&_ctx.encoder, &sd[_i]);                             /*########c*/
	}                                                                        /*########@*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_ADV_UPDATE_DATA_RPC_CMD,      /*####%BHqc*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@6aY*/

	return _result;                                                          /*##BX7TDLc*/
}


void bt_le_ext_adv_cb_enc(CborEncoder *_encoder, struct bt_le_ext_adv_cb *_data) /*####%Bv4Q*/
{                                                                                /*#####@y84*/

	SERIALIZE(STRUCT(struct bt_le_ext_adv_cb));

	ser_encode_callback(&_ctx.encoder, _data->sent);                         /*######%A2*/
	ser_encode_callback(&_ctx.encoder, _data->connected);                    /*######Ydv*/
	ser_encode_callback(&_ctx.encoder, _data->scanned);                      /*######@NM*/

}                                                                                /*##B9ELNqo*/

struct bt_le_ext_adv_create_rpc_res                                              /*####%Bm6e*/
{                                                                                /*#####@dOE*/

	int _result;                                                             /*####%CRV7*/
	struct bt_le_ext_adv ** adv;                                             /*#####@36w*/

};                                                                               /*##B985gv0*/

static void bt_le_ext_adv_create_rpc_rsp(CborValue *_value, void *_handler_data)  /*####%Bno+*/
{                                                                                 /*#####@e2c*/

	struct entropy_get_result *_res =                                         /*####%AWti*/
		(struct bt_le_ext_adv_create_rpc_res *)_handler_data;             /*#####@L2Q*/

	_res->_result = ser_decode_int(_value);                                   /*####%DfFr*/
	*(_res->adv) = (struct bt_le_ext_adv *)(uintptr_t)ser_decode_uint(_value);/*#####@lr4*/

}                                                                                 /*##B9ELNqo*/


int bt_le_ext_adv_create(const struct bt_le_adv_param *param,
			 const struct bt_le_ext_adv_cb *cb,
			 struct bt_le_ext_adv **adv)
{
	SERIALIZE(OUT(adv));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%Ac*/
	struct bt_le_ext_adv_create_rpc_res _result;                             /*#######/y*/
	size_t _scratchpad_size = 0;                                             /*#######a4*/
	size_t _buffer_size_max = 42;                                            /*#######@I*/

	_buffer_size_max += bt_le_adv_param_buf_size(param);                     /*##CKvr4W4*/

	_scratchpad_size += bt_le_adv_param_sp_size(param);                      /*##EEZ/Gv4*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*####%AoDN*/
	ser_encode_uint(&_ctx.encoder, _scratchpad_size);                        /*#####@BNc*/

	bt_le_adv_param_enc(&_ctx.encoder, param);                               /*####%A7sT*/
	bt_le_ext_adv_cb_enc(&_ctx.encoder, cb);                                 /*#####@fDU*/

	_result.adv = adv;                                                       /*##Cx5Tf1c*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_EXT_ADV_CREATE_RPC_CMD,       /*####%BOJo*/
		&_ctx, bt_le_ext_adv_create_rpc_rsp, &_result);                  /*#####@vEw*/

	return _result._result;                                                  /*##BW0ge3U*/
}

void bt_le_ext_adv_start_param_enc(CborEncoder *_encoder, struct bt_le_ext_adv_start_param *_data)/*####%BiBT*/
{                                                                                                 /*#####@q7M*/

	SERIALIZE(STRUCT(struct bt_le_ext_adv_start_param));

	ser_encode_uint(_encoder, _data->timeout);                                                /*####%A4oh*/
	ser_encode_uint(_encoder, _data->num_events);                                             /*#####@m6E*/

}                                                                                                 /*##B9ELNqo*/

int bt_le_ext_adv_start(struct bt_le_ext_adv *adv,
			struct bt_le_ext_adv_start_param *param)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%Ac*/
	int _result;                                                             /*######PRx*/
	size_t _buffer_size_max = 10;                                            /*######@Yo*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_uint(&_ctx.encoder, (uintptr_t)adv);                          /*####%A3ca*/
	bt_le_ext_adv_start_param_enc(&_ctx.encoder, param);                     /*#####@wyE*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_EXT_ADV_START_RPC_CMD,        /*####%BFEC*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@ryw*/

	return _result;                                                          /*##BX7TDLc*/
}


int bt_le_ext_adv_stop(struct bt_le_ext_adv *adv)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%Aa*/
	int _result;                                                             /*######Qso*/
	size_t _buffer_size_max = 5;                                             /*######@uA*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_uint(&_ctx.encoder, (uintptr_t)adv);                          /*##A7bUUXs*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_EXT_ADV_STOP_RPC_CMD,         /*####%BAJN*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@JxE*/

	return _result;                                                          /*##BX7TDLc*/
}


int bt_le_ext_adv_set_data(struct bt_le_ext_adv *adv,
			   const struct bt_data *ad, size_t ad_len,
			   const struct bt_data *sd, size_t sd_len)
{
	SERIALIZE(SIZE_PARAM(ad, ad_len));
	SERIALIZE(SIZE_PARAM(sd, sd_len));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*#######%A*/
	int _result;                                                             /*#######ci*/
	size_t _scratchpad_size = 0;                                             /*#######Rw*/
	size_t _buffer_size_max = 20;                                            /*#######Eo*/
	size_t _i;                                                               /*########@*/

	for (_i = 0; _i < ad_len; _i++) {                                        /*########%*/
		_buffer_size_max += bt_data_buf_size(&ad[_i]);                   /*########C*/
		_scratchpad_size += SCRATCHPAD_ALIGN(sizeof(struct bt_data));    /*########J*/
		_scratchpad_size += bt_data_sp_size(&ad[_i]);                    /*########/*/
	}                                                                        /*########m*/
	for (_i = 0; _i < sd_len; _i++) {                                        /*########7*/
		_buffer_size_max += bt_data_buf_size(&sd[_i]);                   /*########f*/
		_scratchpad_size += SCRATCHPAD_ALIGN(sizeof(struct bt_data));    /*########M*/
		_scratchpad_size += bt_data_sp_size(&sd[_i]);                    /*#########*/
	}                                                                        /*########@*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*####%AoDN*/
	ser_encode_uint(&_ctx.encoder, _scratchpad_size);                        /*#####@BNc*/

	ser_encode_uint(&_ctx.encoder, (uintptr_t)adv);                          /*########%*/
	ser_encode_uint(&_ctx.encoder, ad_len);                                  /*########A*/
	for (_i = 0; _i < ad_len; _i++) {                                        /*########3*/
		bt_data_enc(&_ctx.encoder, &ad[_i]);                             /*########m*/
	}                                                                        /*########T*/
	ser_encode_uint(&_ctx.encoder, sd_len);                                  /*########w*/
	for (_i = 0; _i < sd_len; _i++) {                                        /*########G*/
		bt_data_enc(&_ctx.encoder, &sd[_i]);                             /*########Q*/
	}                                                                        /*########@*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_EXT_ADV_SET_DATA_RPC_CMD,     /*####%BGCj*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@0sg*/

	return _result;                                                          /*##BX7TDLc*/
}


int bt_le_ext_adv_update_param(struct bt_le_ext_adv *adv,
			       const struct bt_le_adv_param *param)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AQ*/
	int _result;                                                             /*#######Bt*/
	size_t _scratchpad_size = 0;                                             /*#######o4*/
	size_t _buffer_size_max = 32;                                            /*#######@s*/

	_buffer_size_max += bt_le_adv_param_buf_size(param);                     /*##CKvr4W4*/

	_scratchpad_size += bt_le_adv_param_sp_size(param);                      /*##EEZ/Gv4*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*####%AoDN*/
	ser_encode_uint(&_ctx.encoder, _scratchpad_size);                        /*#####@BNc*/

	ser_encode_uint(&_ctx.encoder, (uintptr_t)adv);                          /*####%A82t*/
	bt_le_adv_param_enc(&_ctx.encoder, param);                               /*#####@9JA*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_EXT_ADV_UPDATE_PARAM_RPC_CMD, /*####%BBz+*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@6Kg*/

	return _result;                                                          /*##BX7TDLc*/
}

int bt_le_ext_adv_delete(struct bt_le_ext_adv *adv)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%Aa*/
	int _result;                                                             /*######Qso*/
	size_t _buffer_size_max = 5;                                             /*######@uA*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_uint(&_ctx.encoder, (uintptr_t)adv);                          /*##A7bUUXs*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_EXT_ADV_DELETE_RPC_CMD,       /*####%BKnQ*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@zKE*/

	return _result;                                                          /*##BX7TDLc*/
}


uint8_t bt_le_ext_adv_get_index(struct bt_le_ext_adv *adv)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%Ac*/
	uint8_t _result;                                                         /*######lxx*/
	size_t _buffer_size_max = 5;                                             /*######@q0*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_uint(&_ctx.encoder, (uintptr_t)adv);                          /*##A7bUUXs*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_EXT_ADV_GET_INDEX_RPC_CMD,    /*####%BK4M*/
		&_ctx, ser_rsp_simple_u8, &_result);                             /*#####@Hi8*/

	return _result;                                                          /*##BX7TDLc*/
}

void bt_le_ext_adv_info_dec(CborValue *_value, struct bt_le_ext_adv_info *_data) /*####%BvJh*/
{                                                                                /*#####@D8M*/

	_data->id = ser_decode_uint(_value);                                     /*####%CvH0*/
	_data->tx_power = ser_decode_int(_value);                                /*#####@OLs*/

}                                                                                /*##B9ELNqo*/

struct bt_le_ext_adv_get_info_rpc_res                                            /*####%BtHv*/
{                                                                                /*#####@AD0*/

	int _result;                                                             /*####%CU6/*/
	struct bt_le_ext_adv_info * info;                                        /*#####@vlc*/

};                                                                               /*##B985gv0*/

static void bt_le_ext_adv_get_info_rpc_rsp(CborValue *_value, void *_handler_data)/*####%BhTB*/
{                                                                                 /*#####@DEk*/

	struct entropy_get_result *_res =                                         /*####%AR5V*/
		(struct bt_le_ext_adv_get_info_rpc_res *)_handler_data;           /*#####@d9A*/

	_res->_result = ser_decode_int(_value);                                   /*####%DVh4*/
	bt_le_ext_adv_info_dec(_value, _res->info);                               /*#####@cvQ*/

}                                                                                 /*##B9ELNqo*/

int bt_le_ext_adv_get_info(const struct bt_le_ext_adv *adv,
			   struct bt_le_ext_adv_info *info)
{
	SERIALIZE(OUT(info));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AQ*/
	struct bt_le_ext_adv_get_info_rpc_res _result;                           /*######uj1*/
	size_t _buffer_size_max = 5;                                             /*######@40*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_uint(&_ctx.encoder, (uintptr_t)adv);                          /*##A7bUUXs*/

	_result.info = info;                                                     /*##C65VXp0*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_EXT_ADV_GET_INFO_RPC_CMD,     /*####%BNVz*/
		&_ctx, bt_le_ext_adv_get_info_rpc_rsp, &_result);                /*#####@93Y*/

	return _result._result;                                                  /*##BW0ge3U*/
}

void bt_le_scan_param_enc(CborEncoder *_encoder, struct bt_le_scan_param *_data) /*####%BtCb*/
{                                                                                /*#####@haw*/

	SERIALIZE(STRUCT(struct bt_le_scan_param));

	ser_encode_uint(_encoder, _data->type);                                  /*#######%A*/
	ser_encode_uint(_encoder, _data->options);                               /*#######4W*/
	ser_encode_uint(_encoder, _data->interval);                              /*########D*/
	ser_encode_uint(_encoder, _data->window);                                /*########I*/
	ser_encode_uint(_encoder, _data->timeout);                               /*########n*/
	ser_encode_uint(_encoder, _data->interval_coded);                        /*########Q*/
	ser_encode_uint(_encoder, _data->window_coded);                          /*########@*/

}                                                                                /*##B9ELNqo*/


int bt_le_scan_start(const struct bt_le_scan_param *param, bt_le_scan_cb_t cb)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AR*/
	int _result;                                                             /*######PI0*/
	size_t _buffer_size_max = 27;                                            /*######@Mk*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	bt_le_scan_param_enc(&_ctx.encoder, param);                              /*####%A+tp*/
	ser_encode_callback(&_ctx.encoder, cb);                                  /*#####@nI8*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_SCAN_START_RPC_CMD,           /*####%BEk6*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@M28*/

	return _result;                                                          /*##BX7TDLc*/
}


int bt_le_whitelist_add(const bt_addr_le_t *addr)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AR*/
	int _result;                                                             /*######RDP*/
	size_t _buffer_size_max = 3;                                             /*######@sI*/

	_buffer_size_max += addr ? sizeof(bt_addr_le_t) : 0;                     /*##CHCgvU0*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_buffer(&_ctx.encoder, addr, sizeof(bt_addr_le_t));            /*##A9rQrRg*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_WHITELIST_ADD_RPC_CMD,        /*####%BOf6*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@eVE*/

	return _result;                                                          /*##BX7TDLc*/
}

int bt_le_whitelist_rem(const bt_addr_le_t *addr)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AR*/
	int _result;                                                             /*######RDP*/
	size_t _buffer_size_max = 3;                                             /*######@sI*/

	_buffer_size_max += addr ? sizeof(bt_addr_le_t) : 0;                     /*##CHCgvU0*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_buffer(&_ctx.encoder, addr, sizeof(bt_addr_le_t));            /*##A9rQrRg*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_WHITELIST_REM_RPC_CMD,        /*####%BI9r*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@j9w*/

	return _result;                                                          /*##BX7TDLc*/
}


void bt_data_parse(struct net_buf_simple *ad,
		   bool (*func)(struct bt_data *data, void *user_data),
		   void *user_data)
{
	while (ad->len > 1) {
		struct bt_data data;
		u8_t len;

		len = net_buf_simple_pull_u8(ad);
		if (len == 0U) {
			/* Early termination */
			return;
		}

		if (len > ad->len) {
			BT_WARN("Malformed data");
			return;
		}

		data.type = net_buf_simple_pull_u8(ad);
		data.data_len = len - 1;
		data.data = ad->data;

		if (!func(&data, user_data)) {
			return;
		}

		net_buf_simple_pull(ad, len - 1);
	}
}

void bt_le_oob_dec(CborValue *_value, struct bt_le_oob *_data)                   /*####%BguA*/
{                                                                                /*#####@olA*/

	ser_decode_buffer(_value, &_data->bt_addr_le_t, sizeof(bt_addr_le_t));   /*######%Cp*/
	ser_decode_buffer(_value, _data->le_sc_data.r, 16 * sizeof(uint8_t));    /*######mgn*/
	ser_decode_buffer(_value, _data->le_sc_data.c, 16 * sizeof(uint8_t));    /*######@hg*/

}                                                                                /*##B9ELNqo*/

struct bt_le_oob_get_local_rpc_res                                               /*####%BtvS*/
{                                                                                /*#####@LW8*/

	int _result;                                                             /*####%CXk/*/
	struct bt_le_oob * oob;                                                  /*#####@aJI*/

};                                                                               /*##B985gv0*/

static void bt_le_oob_get_local_rpc_rsp(CborValue *_value, void *_handler_data)  /*####%BkkP*/
{                                                                                /*#####@R00*/

	struct entropy_get_result *_res =                                        /*####%ARRD*/
		(struct bt_le_oob_get_local_rpc_res *)_handler_data;             /*#####@K3w*/

	_res->_result = ser_decode_int(_value);                                  /*####%DR/C*/
	bt_le_oob_dec(_value, _res->oob);                                        /*#####@FlU*/

}                                                                                /*##B9ELNqo*/

int bt_le_oob_get_local(uint8_t id, struct bt_le_oob *oob)
{
	SERIALIZE(OUT(oob));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%Ac*/
	struct bt_le_oob_get_local_rpc_res _result;                              /*######0n1*/
	size_t _buffer_size_max = 2;                                             /*######@dw*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_uint(&_ctx.encoder, id);                                      /*##A9BnOB4*/

	_result.oob = oob;                                                       /*##C1H7kLY*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_OOB_GET_LOCAL_RPC_CMD,        /*####%BP2i*/
		&_ctx, bt_le_oob_get_local_rpc_rsp, &_result);                   /*#####@okg*/

	return _result._result;                                                  /*##BW0ge3U*/
}


struct bt_le_ext_adv_oob_get_local_rpc_res                                       /*####%BiEN*/
{                                                                                /*#####@OIM*/

	int _result;                                                             /*####%CXk/*/
	struct bt_le_oob * oob;                                                  /*#####@aJI*/

};                                                                               /*##B985gv0*/

static void bt_le_ext_adv_oob_get_local_rpc_rsp(CborValue *_value, void *_handler_data)/*####%Bip2*/
{                                                                                      /*#####@zQs*/

	struct entropy_get_result *_res =                                              /*####%Acbd*/
		(struct bt_le_ext_adv_oob_get_local_rpc_res *)_handler_data;           /*#####@iRE*/

	_res->_result = ser_decode_int(_value);                                        /*####%DR/C*/
	bt_le_oob_dec(_value, _res->oob);                                              /*#####@FlU*/

}                                                                                      /*##B9ELNqo*/

int bt_le_ext_adv_oob_get_local(struct bt_le_ext_adv *adv,
				struct bt_le_oob *oob)
{
	SERIALIZE(OUT(oob));

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%AQ*/
	struct bt_le_ext_adv_oob_get_local_rpc_res _result;                      /*######Ppb*/
	size_t _buffer_size_max = 5;                                             /*######@OI*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_uint(&_ctx.encoder, (uintptr_t)adv);                          /*##A7bUUXs*/

	_result.oob = oob;                                                       /*##C1H7kLY*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_LE_EXT_ADV_OOB_GET_LOCAL_RPC_CMD,/*####%BDti*/
		&_ctx, bt_le_ext_adv_oob_get_local_rpc_rsp, &_result);           /*#####@wh8*/

	return _result._result;                                                  /*##BW0ge3U*/
}


int bt_unpair(uint8_t id, const bt_addr_le_t *addr)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*######%Aa*/
	int _result;                                                             /*######Qso*/
	size_t _buffer_size_max = 5;                                             /*######@uA*/

	_buffer_size_max += addr ? sizeof(bt_addr_le_t) : 0;                     /*##CHCgvU0*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_uint(&_ctx.encoder, id);                                      /*####%A3Ax*/
	ser_encode_buffer(&_ctx.encoder, addr, sizeof(bt_addr_le_t));            /*#####@8HM*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_UNPAIR_RPC_CMD,                  /*####%BLf4*/
		&_ctx, ser_rsp_simple_i32, &_result);                            /*#####@xD4*/

	return _result;                                                          /*##BX7TDLc*/
}


void bt_foreach_bond(uint8_t id, bt_foreach_bond_func_t func, void *user_data)
{
	SERIALIZE();

	struct nrf_rpc_cbor_ctx _ctx;                                            /*####%AYVb*/
	size_t _buffer_size_max = 12;                                            /*#####@PYw*/

	NRF_RPC_CBOR_ALLOC(_ctx, _buffer_size_max);                              /*##AvrU03s*/

	ser_encode_uint(&_ctx.encoder, id);                                      /*######%A8*/
	ser_encode_callback(&_ctx.encoder, func);                                /*######9qY*/
	ser_encode_uint(&_ctx.encoder, (uintptr_t)user_data);                    /*######@D0*/

	nrf_rpc_cbor_cmd_no_err(&bt_rpc_grp, BT_FOREACH_BOND_RPC_CMD,            /*####%BHJx*/
		&_ctx, ser_rsp_simple_void, NULL);                               /*#####@aas*/
}

static void bt_foreach_bond_func_t_encoder_rpc_handler(CborValue *_value, void *_handler_data)/*####%BhnC*/
{                                                                                             /*#####@fVM*/

	bt_foreach_bond_func_t callback_slot;                                                 /*######%AU*/
	struct bt_bond_info _info_data;                                                       /*#######QJ*/
	const struct bt_bond_info * info;                                                     /*#######Co*/
	void * user_data;                                                                     /*#######@E*/

	callback_slot = (bt_foreach_bond_func_t)ser_decode_callback_slot(_value);             /*######%Cp*/
	info = ser_decode_buffer(_value, &_info_data, sizeof(struct bt_bond_info));           /*######loS*/
	user_data = (void *)ser_decode_uint(_value);                                          /*######@uY*/

	if (!ser_decoding_done_and_check(_value)) {                                           /*######%AE*/
		goto decoding_error;                                                          /*######QTM*/
	}                                                                                     /*######@1Y*/

	callback_slot(info, user_data);                                                       /*##DpwAqyg*/

	ser_rsp_send_void();                                                                  /*##BEYGLxw*/

	return;                                                                               /*######%B1*/
decoding_error:                                                                               /*#######Qe*/
	report_decoding_error(BT_FOREACH_BOND_FUNC_T_ENCODER_RPC_CMD, _handler_data);         /*#######zo*/
}                                                                                             /*#######@U*/

static void bt_ready_cb_t_encoder_rpc_handler(CborValue *_value, void *_handler_data)/*####%BmU8*/
{                                                                                    /*#####@JaA*/

	bt_ready_cb_t callback_slot;                                                 /*####%AVZM*/
	int err;                                                                     /*#####@ksU*/

	callback_slot = (bt_ready_cb_t)ser_decode_callback_slot(_value);             /*####%ClOC*/
	err = ser_decode_int(_value);                                                /*#####@KRE*/

	if (!ser_decoding_done_and_check(_value)) {                                  /*######%AE*/
		goto decoding_error;                                                 /*######QTM*/
	}                                                                            /*######@1Y*/

	callback_slot(err);                                                          /*##DnrVhJE*/

	return;                                                                      /*######%Bz*/
decoding_error:                                                                      /*#######0D*/
	report_decoding_error(BT_READY_CB_T_ENCODER_RPC_EVT, _handler_data);         /*#######ax*/
}                                                                                    /*#######@c*/

struct net_buf_simple {
	/** Pointer to the start of data in the buffer. */
	u8_t *data;

	/** Length of the data behind the data pointer. */
	u16_t len;

	/** Amount of data that this buffer can store. */
	u16_t size;

	/** Start of the data storage. Not to be accessed directly
	 *  (the data pointer should be used instead).
	 */
	u8_t *__buf;
};

void net_buf_simple_dec(struct ser_scratchpad *_scratchpad, struct net_buf_simple *_data)
{
	CborValue *_value = _scratchpad->value;

	_data->len = ser_decode_buffer_size(_value);
	_data->data = ser_decode_buffer_sp(_scratchpad);
	_data->size = _data->len;
	_data->__buf = _data->data;
}

void bt_le_scan_recv_info_dec(struct ser_scratchpad *_scratchpad, struct bt_le_scan_recv_info *_data)/*####%BpcV*/
{                                                                                                    /*#####@rYc*/

	CborValue *_value = _scratchpad->value;                                                      /*##AU3cSLw*/

	_data->addr = ser_decode_buffer_sp(_scratchpad);                                             /*#######%C*/
	_data->sid = ser_decode_uint(_value);                                                        /*########l*/
	_data->rssi = ser_decode_int(_value);                                                        /*########l*/
	_data->tx_power = ser_decode_int(_value);                                                    /*########D*/
	_data->adv_type = ser_decode_uint(_value);                                                   /*########+*/
	_data->adv_props = ser_decode_uint(_value);                                                  /*########C*/
	_data->primary_phy = ser_decode_uint(_value);                                                /*########Q*/
	_data->secondary_phy = ser_decode_uint(_value);                                              /*########@*/

}                                                                                                    /*##B9ELNqo*/

static void bt_le_scan_recv_rpc_handler(CborValue *_value, void *_handler_data)  /*####%Bh/u*/
{                                                                                /*#####@bIo*/

	struct bt_le_scan_recv_info info;                                        /*######%AU*/
	struct net_buf_simple buf;                                               /*######QJk*/
	struct ser_scratchpad _scratchpad;                                       /*######@yc*/

	SER_SCRATCHPAD_ALLOC(&_scratchpad, _value);                              /*##EZKHjKY*/

	bt_le_scan_recv_info_dec(&_scratchpad, &info);                           /*####%Cjth*/
	net_buf_simple_dec(&_scratchpad, &buf);                                  /*#####@XMc*/

	if (!ser_decoding_done_and_check(_value)) {                              /*######%AE*/
		goto decoding_error;                                             /*######QTM*/
	}                                                                        /*######@1Y*/

	bt_le_scan_recv(&info, &buf);                                            /*##Dk7Zjs4*/

	SER_SCRATCHPAD_FREE(&_scratchpad);                                       /*##Eq1r7Tg*/

	ser_rsp_send_void();                                                     /*##BEYGLxw*/

	return;                                                                  /*#######%B*/
decoding_error:                                                                  /*#######xO*/
	report_decoding_error(BT_LE_SCAN_RECV_RPC_CMD, _handler_data);           /*#######iW*/
	SER_SCRATCHPAD_FREE(&_scratchpad);                                       /*#######hc*/
}                                                                                /*########@*/

SERIALIZE(STRUCT_BUFFER_CONST(bt_le_adv_param, 22));                             /*##BpIi8ZQ*/

SERIALIZE(STRUCT_BUFFER_CONST(bt_data, 9));                                      /*##BpOvlm4*/

SERIALIZE(STRUCT_BUFFER_CONST(bt_le_ext_adv_cb, 15));                            /*##BvnMgB0*/

SERIALIZE(STRUCT_BUFFER_CONST(bt_le_ext_adv_start_param, 5));                    /*##Bh2tuzU*/

SERIALIZE(STRUCT_BUFFER_CONST(bt_le_scan_param, 22));                            /*##BvJvxzY*/

void bt_le_ext_adv_connected_info_dec(CborValue *_value, struct bt_le_ext_adv_connected_info *_data)/*####%BqU2*/
{                                                                                                   /*#####@mSw*/

	_data->conn = (struct bt_conn *)(uintptr_t)ser_decoder_uint(_value);                        /*##CvUiOl0*/

}                                                                                                   /*##B9ELNqo*/

static void bt_le_ext_adv_cb_sent_t_encoder_rpc_handler(CborValue *_value, void *_handler_data)/*####%BkWG*/
{                                                                                              /*#####@igE*/

	bt_le_ext_adv_cb_sent_t callback_slot;                                                 /*######%AS*/
	struct bt_le_ext_adv * adv;                                                            /*#######AL*/
	struct bt_le_ext_adv_sent_info _info_data;                                             /*#######ak*/
	struct bt_le_ext_adv_sent_info * info;                                                 /*#######@E*/

	callback_slot = (bt_le_ext_adv_cb_sent_t)ser_decode_callback_slot(_value);             /*######%Cu*/
	adv = (struct bt_le_ext_adv *)ser_decode_uint(_value);                                 /*######ECV*/
	info = ser_decode_buffer(_value, &_info_data, sizeof(struct bt_le_ext_adv_sent_info)); /*######@vc*/

	if (!ser_decoding_done_and_check(_value)) {                                            /*######%AE*/
		goto decoding_error;                                                           /*######QTM*/
	}                                                                                      /*######@1Y*/

	callback_slot(adv, info);                                                              /*##DvcoVkc*/

	ser_rsp_send_void();                                                                   /*##BEYGLxw*/

	return;                                                                                /*######%B4*/
decoding_error:                                                                                /*#######2v*/
	report_decoding_error(BT_LE_EXT_ADV_CB_SENT_T_ENCODER_RPC_CMD, _handler_data);         /*#######sK*/
}                                                                                              /*#######@g*/

static void bt_le_ext_adv_cb_connected_t_encoder_rpc_handler(CborValue *_value, void *_handler_data)/*####%Bqla*/
{                                                                                                   /*#####@eDs*/

	bt_le_ext_adv_cb_connected_t callback_slot;                                                 /*######%AZ*/
	struct bt_le_ext_adv * adv;                                                                 /*######EN0*/
	struct bt_le_ext_adv_connected_info info;                                                   /*######@vI*/

	callback_slot = (bt_le_ext_adv_cb_connected_t)ser_decode_callback_slot(_value);             /*######%Cu*/
	adv = (struct bt_le_ext_adv *)ser_decode_uint(_value);                                      /*######ObH*/
	bt_le_ext_adv_connected_info_dec(_value, &info);                                            /*######@s4*/

	if (!ser_decoding_done_and_check(_value)) {                                                 /*######%AE*/
		goto decoding_error;                                                                /*######QTM*/
	}                                                                                           /*######@1Y*/

	callback_slot(adv, &info);                                                                  /*##DmH3+Xw*/

	ser_rsp_send_void();                                                                        /*##BEYGLxw*/

	return;                                                                                     /*######%B8*/
decoding_error:                                                                                     /*#######I2*/
	report_decoding_error(BT_LE_EXT_ADV_CB_CONNECTED_T_ENCODER_RPC_CMD, _handler_data);         /*#######Xi*/
}                                                                                                   /*#######@I*/

static void bt_le_ext_adv_cb_scanned_t_encoder_rpc_handler(CborValue *_value, void *_handler_data)/*####%BslI*/
{                                                                                                 /*#####@JWM*/

	bt_le_ext_adv_cb_scanned_t callback_slot;                                                 /*######%AW*/
	struct bt_le_ext_adv * adv;                                                               /*#######Re*/
	struct bt_le_ext_adv_scanned_info _info_data;                                             /*#######h0*/
	struct bt_le_ext_adv_scanned_info * info;                                                 /*#######@Y*/

	callback_slot = (bt_le_ext_adv_cb_scanned_t)ser_decode_callback_slot(_value);             /*######%Cn*/
	adv = (struct bt_le_ext_adv *)ser_decode_uint(_value);                                    /*######BxG*/
	info = ser_decode_buffer(_value, &_info_data, sizeof(struct bt_le_ext_adv_scanned_info)); /*######@LI*/

	if (!ser_decoding_done_and_check(_value)) {                                               /*######%AE*/
		goto decoding_error;                                                              /*######QTM*/
	}                                                                                         /*######@1Y*/

	callback_slot(adv, info);                                                                 /*##DvcoVkc*/

	ser_rsp_send_void();                                                                      /*##BEYGLxw*/

	return;                                                                                   /*######%B2*/
decoding_error:                                                                                   /*#######Dw*/
	report_decoding_error(BT_LE_EXT_ADV_CB_SCANNED_T_ENCODER_RPC_CMD, _handler_data);         /*#######85*/
}                                                                                                 /*#######@A*/

NRF_RPC_CBOR_CMD_DECODER(bt_rpc_grp, bt_ready_cb_t_encoder, BT_READY_CB_T_ENCODER_RPC_EVT,/*####%BvSP*/
	bt_ready_cb_t_encoder_rpc_handler, NULL);                                         /*#####@hs8*/

NRF_RPC_CBOR_CMD_DECODER(bt_rpc_grp, bt_le_scan_recv, BT_LE_SCAN_RECV_RPC_CMD,   /*####%BrM0*/
	bt_le_scan_recv_rpc_handler, NULL);                                      /*#####@CgQ*/

NRF_RPC_CBOR_CMD_DECODER(bt_rpc_grp, bt_le_scan_timeout, BT_LE_SCAN_TIMEOUT_RPC_EVT,/*####%BtsC*/
	bt_le_scan_timeout_rpc_handler, NULL);                                      /*#####@wgs*/

NRF_RPC_CBOR_CMD_DECODER(bt_rpc_grp, bt_le_ext_adv_cb_sent_t_encoder, BT_LE_EXT_ADV_CB_SENT_T_ENCODER_RPC_CMD,/*####%Bh1I*/
	bt_le_ext_adv_cb_sent_t_encoder_rpc_handler, NULL);                                                   /*#####@QBc*/

NRF_RPC_CBOR_CMD_DECODER(bt_rpc_grp, bt_le_ext_adv_cb_connected_t_encoder, BT_LE_EXT_ADV_CB_CONNECTED_T_ENCODER_RPC_CMD,/*####%BnBP*/
	bt_le_ext_adv_cb_connected_t_encoder_rpc_handler, NULL);                                                        /*#####@AtM*/

NRF_RPC_CBOR_CMD_DECODER(bt_rpc_grp, bt_le_ext_adv_cb_scanned_t_encoder, BT_LE_EXT_ADV_CB_SCANNED_T_ENCODER_RPC_CMD,/*####%BtPf*/
	bt_le_ext_adv_cb_scanned_t_encoder_rpc_handler, NULL);                                                      /*#####@KGA*/

NRF_RPC_CBOR_CMD_DECODER(bt_rpc_grp, bt_foreach_bond_func_t_encoder, BT_FOREACH_BOND_FUNC_T_ENCODER_RPC_CMD,/*####%Bnqa*/
	bt_foreach_bond_func_t_encoder_rpc_handler, NULL);                                                  /*#####@Ol4*/

